### ISSUE TITLE
Taxonomy of Attacks on Open-Source Software Supply Chains

### ISSUE THREAD

**Issue by henrikplate** [bureado/awesome-software-supply-chain-security#27]
fyi - Starting from the attack tree in [Fig.2 of the Backstabber's Knife Collection](https://arxiv.org/pdf/2005.09535.pdf), we propose a more comprehensive overview about the attack surface of software supply chains in [Taxonomy of Attacks on Open-Source Software Supply Chains](https://arxiv.org/abs/2204.04008). This taxonomy with ~100 attack vectors has been validated by domain experts and is linked to corresponding safeguards.

**Comment by piergiorgioladisa** [comment]
> 



> fyi - Starting from the attack tree in [Fig.2 of the Backstabber's Knife Collection](https://arxiv.org/pdf/2005.09535.pdf), we propose a more comprehensive overview about the attack surface of software supply chains in [Taxonomy of Attacks on Open-Source Software Supply Chains](https://arxiv.org/abs/2204.04008). This taxonomy with ~100 attack vectors has been validated by domain experts and is linked to corresponding safeguards.

The taxonomy (and related resources) can be also inspected with more details through the [Risk Explorer for Software Supply Chains](https://sap.github.io/risk-explorer-for-software-supply-chains/). Being open-source it can be improved as soon as new attacks will appear in the space of OSS supply chain attacks.

**Comment by kpcyrd** [comment]
Cool graph! I've opened an issue to add binary transparency (https://github.com/SAP/risk-explorer-for-software-supply-chains/issues/53). I don't get the "safeguard" feature though, selecting SBOM makes every line green and I'm not sure if that implies an sbom fixes everything. :)

**Comment by piergiorgioladisa** [comment]
> Cool graph! I've opened an issue to add binary transparency ([SAP/risk-explorer-for-software-supply-chains#53](https://github.com/SAP/risk-explorer-for-software-supply-chains/issues/53)). I don't get the "safeguard" feature though, selecting SBOM makes every line green and I'm not sure if that implies an sbom fixes everything. :)

We're glad you like it and thanks for opening the issue, this is exactly the feedback and collaboration we seek to have! 
The safeguard feature has to be intended to show in the graph where a certain countermeasure/safeguard/best-practice is mapped. Nevertheless, this doesn't mean that using a certain countermeasure fully prevents certain attacks, but it just mean that can partially mitigate that attack vector. In the case of SBOM we discussed a lot among us and we thought the good fit was to map it directly to the root-node of the tree. But if you think this is not correctly mapped we can discuss it in an issue section of the Risk Explorer repository
